Maksim Anikhovskiy labs
PashaKlybik/prog_953504 pull request #2
Opened 2020-03-21 10:12 UTC by MaksTandarT

2020-03-27 07:11 UTC, PashaKlybik requested changes
Убрать файлы расширения *exe и остальные, оставить только файлы с лабораторными

2020-03-27 08:02 UTC, MaksTandarT commented
Сделал

2020-03-27 08:57 UTC, PashaKlybik requested changes
А где вторая часть четвертой лабы?

2020-03-27 11:05 UTC, MaksTandarT commented
её нет, я сначала не думал её пушить, но потом подумал, мало ли, вам пригодится, или мне. Я пока занимаюсь проектом на JS, так что дальше того, что вы можете увидеть в моём PR я ничего пока не делал. Если нужно будет сделать, выделю себе на это одну ночь.

2020-04-08 16:11 UTC, MaksTandarT commented
Добавил лабу 4-2

2020-05-10 08:29 UTC, PashaKlybik commented
принято

2020-05-10 08:30 UTC, merged